### ISSUE TITLE
Sonos could not play .mp3, could not connect to MYIP:1980

### ISSUE THREAD

**Issue by SmartHomeNewbie** [Supergiovane/node-red-contrib-tts-ultimate#13]
Hello.

I've been battling with this node for a few days now and can't figure out what I'm doing wrong.

I'm running node red in docker
Port 1980 is forwarded to the IP of the raspberry node-red is running on
1400 is forwarded to  IP of my sonos speaker (i have also tried to forward it to the node-red IP)
When i edit the config i get this error: "ttsultimate-config: Error in discovery Error: No device found" but when i manually write IP of my sonos speaker, the node shows "sonos is connected"
 
So the problem is that when i try to send a message to my sonos speaker, i get an error in sonos app, 'cannot play tts.mp3.blabla.mp3' -  could not connect to myip:1980

Could you point me in the right direction with the info provided? else ill me know what you need! thanks

**Comment by Supergiovane** [comment]
Hi
The discovery error is probably due to the mdns filtered out by docker. After a while, the node reverts to manual configuration via ip text fields. 
About the other issue, your sonos device is unable to reach nodered. 
Double check the inbound docker port you forwarded to nodered. Take a screenshot of docker config and paste it here. 
Always avoid using docker if possible. Use raspberry as is (there is a nodered installation done exactly for raspbian), or use a VM instead.

**Comment by SmartHomeNewbie** [comment]
Thank you for the reply.

i've made a screenshot of my port forwarding. im using the default port 1980.

![router](https://user-images.githubusercontent.com/75638271/107140925-bd907700-6925-11eb-8ce5-0d9b50c5a429.jpg)



As for the "docker config" i had no clue what or where it was, i googled and found "deamon.json" file in /etc/docker/
Is that what you where asking for ?

![deamon json](https://user-images.githubusercontent.com/75638271/107140966-16f8a600-6926-11eb-83b8-f4b81e2acbeb.jpg)

**Comment by Supergiovane** [comment]
Hi
why you have two different IPs, 0.146 and 0.113?
What is exactly the IP of node-red and the IP of your Docker?
As "myip" in your prev post, you need to set the docker's IP.

**Comment by SmartHomeNewbie** [comment]
146 ip of my sonos speaker and 113 is the raspberry im running docker on, does the docker container have its own IP insde the respberry?

**Comment by Supergiovane** [comment]
Hi
Set both ip in the docker config, to the 113
I never used docker installed on raspberry, but it can have it’s own IP or working as bridge, depending on configuration. 
if you’re a newbie, i strongly suggest you to install rasbpian and nodered directly into the raspberry pi. 
Otherwise, you should ask to the forum where you downloaded docker, as i’m not aware how docker works in a raspberry pi, sorry!

**Comment by SmartHomeNewbie** [comment]
Thanks for your time!
I guess its too complicated for me to do it while running node-red in docker and im not willing to change my setup just for one node :)
