### ISSUE TITLE
Resume casuses problems on pause

### ISSUE THREAD

**Issue by evazzoler** [Supergiovane/node-red-contrib-tts-ultimate#19]
When i pause (from alexa, sonos app or phisical button ) music from radio streaming and sonos is no longer playing it, in the resume phase of tts-ultimate I hear about 200ms of music.
I suppose this happens when queue is in pause and not empty (it happens almost always if you really use sonos system!).
The solution maybe to check at start the state (play/pause) and decide if trigger resume only if the was is play.

**Comment by Supergiovane** [comment]
Hi Evazzoler
I never heard of this issue. This can be relatet do the speed of your system where node-red is running.
I cannot unfortunately change this behaviour, because the APIs from Sonos are undocumented and the only way to do the resume, is to resume and then to pause. Other than that, it's impossible to detect if a  streaming is a real stream, or a playlist in sort of streaming or so on. Every service (Apple Music, Spotify, Sonos Radio Station...) is different from each other and there is little to no documentation on that.
I suggest you to put the tts-ultimate volume to zero somehow, until resume has finished.Sorry.
