### ISSUE TITLE
Radio station is added in the queue after playing TTS Ultimate

### ISSUE THREAD

**Issue by mark-veenstra** [Supergiovane/node-red-contrib-tts-ultimate#20]
Hi,

Thanks for the great plugin, but I noticed that TTS Ultimate does not restore exactly the previous state. For example when I start listening to an online radio station (from the Juke plugin on Sonos) with the use of the Sonos App. And then when I start TTS Ultimate to play something, afterwards the radio station is added as a queue item instead of just playing the station again.

I guess it's related to the way the previous state is captured and played again. I noticed when using [group.create.snap](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/A.1-Universal-Node#groupcreatesnap) than execute TTS and then do a [group.play.snap](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/A.1-Universal-Node#groupplaysnap) afterwards the original state is played again (without a queue). Maybe this can be done directly in TTS Ultimate?

Mark

**Comment by Supergiovane** [comment]
Hi, thank you for the suggestion.
TTS-Ultimate is focused mainly on the TTS and reliability, while node-red-contrib-sonos-plus shines on music.
Currently, i cannot simply change the underlying functions, because it's used by some alarm manufacturers, but i can take a look at how sonos-plus handles the queues, for a future implementation.
;-)
