### ISSUE TITLE
ownfile not working because of comma

### ISSUE THREAD

**Issue by Vinisz** [Supergiovane/node-red-contrib-tts-ultimate#25]
Hi,

Trying to play own files via the "ownfile" node but sonos says it cannot play the file because it cannot contact 192,168,0,3:1980 (it should be 192.168.0.3:1980)  to be clear, it is looking for 192 comma 168 dot 0 dot 3 instead of 192 dot 168 dot 0 dot 3
How can this happen ?

**Comment by Supergiovane** [comment]
Hi
 tried yet. It works.

<img width="482" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/120321220-55560e80-c2e3-11eb-832a-4a0987584fd3.png">

Are you sure not to have commas instead of points in the config
<img width="490" alt="Node-RED 2" src="https://user-images.githubusercontent.com/37666636/120321270-699a0b80-c2e3-11eb-821a-5e5aac1a4bbb.png">
 window?

**Comment by Vinisz** [comment]
Too easy, thanks for the swift response.... works now
