### ISSUE TITLE
OwnFile upload not working?

### ISSUE THREAD

**Issue by Flight777** [Supergiovane/node-red-contrib-tts-ultimate#3]
Trying to upload files with the Ownfile node does not seem to work? After selecting, the file immediately dissappears and cannot be found in the dropdown list.

Coming from SonosPollyTTS if that makes any difference :)

How can I troubleshoot best?

**Comment by Supergiovane** [comment]
Hi 777
You runs nodered for sure behind something like redmatic, homeassistant etc..
Please be sure, the user running nodered has rigths to write to the filesystem

**Comment by Flight777** [comment]
Nope, it's a direct docker container on UNRAID.

It should have the proper rights, because the delete function does work, which deletes all the example files.

**Comment by Supergiovane** [comment]
Do you upload mp3?

**Comment by Supergiovane** [comment]
Hi
please update to 1.0.6
They tell us exactly what happens, in the debug window.
Thanks.

**Comment by Flight777** [comment]
Here you go:

![install log](https://user-images.githubusercontent.com/5236143/103357873-891ed500-4ab4-11eb-8e80-0d5cf64e015d.PNG)

![log2](https://user-images.githubusercontent.com/5236143/103357886-8fad4c80-4ab4-11eb-81db-5657d8f32e52.PNG)

**Comment by Supergiovane** [comment]
EXDEV issue:
oldpath and newpath are not on the same mounted filesystem. (Linux permits a filesystem to be mounted at multiple points, but rename() does not work across different mount points, even if the same filesystem is mounted on both.)

Will try to workaround this, by copy the file from the temp folder to the new folder and delete the temp file, instead of simply rename it.
Stay tuned...

**Comment by Supergiovane** [comment]
Hi tripleseven
1.0.8 is out in some minutes.
Give it a try.
Thanks.

**Comment by Flight777** [comment]
Working now, thanks for the super fast fix 👍  :)
