### ISSUE TITLE
GOOGLE TTS api configuration

### ISSUE THREAD

**Issue by evazzoler** [Supergiovane/node-red-contrib-tts-ultimate#91]
Hi, I'm following the directions suggested on the WiKi that are linked to [here](https://www.npmjs.com/package/@google-cloud/text-to-speech), and that page is a copy of the official [here](https://cloud.google.com/nodejs/docs/reference/text-to-speech/latest).
Unfortunately nowhere I can find a step-by-step explanation on how to create the credentials (and json file I need for the config).
This is the last step, but I cannot figure out...
I tried different choicesm but I always receive the error

`"ttsultimate: node id: [...] Error Downloading TTS: The incoming JSON object does not contain a client_email field. THE TTS SERVICE MAY BE DOWN."`

Is it possible to have a 3-points explanation for dummies (like me)?

**Comment by Supergiovane** [comment]
Hi Enrico
basically you need a google cloud account. Then you must create an application, then download the credentials.
Sincerely, i've done that years ago and i cannot help you on that, because for sure something has changed inbetween.
<img width="1129" alt="Gestione_risorse_–_Google_Cloud_Console_e_Posta_in_arrivo_•_massimosaccani_icloud_com" src="https://github.com/user-attachments/assets/2362b0ff-ca79-479a-b349-476407ffbf9d">

<img width="1122" alt="Impostazioni_–_IAM_e_amministrazio…_–_noderedTTS_–_Google_Cloud_Console" src="https://github.com/user-attachments/assets/419daa28-bbf3-4b58-a875-01dc1798b382">

**Comment by evazzoler** [comment]
I did that... But, I've casually found now what I was missing:

![immagine](https://github.com/user-attachments/assets/5c042690-205b-4e45-9233-5b32bbc6e65e)
